# Generated by Django 2.1.2 on 2018-10-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonsured', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=250)),
                ('city', models.CharField(choices=[('a', 'New York'), ('b', 'Miami')], max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
