# Generated by Django 2.1.2 on 2018-10-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonsured', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='getquote',
            name='body_style',
            field=models.CharField(choices=[('style1', 'body style 1'), ('style2', 'body style 2')], default='style1', max_length=100),
        ),
        migrations.AddField(
            model_name='getquote',
            name='car_model',
            field=models.CharField(choices=[('3 series', '3 series'), ('X3', 'X3')], default='X3', max_length=100),
        ),
        migrations.AddField(
            model_name='getquote',
            name='contact_date_of_birth',
            field=models.DateField(default='1900-10-10'),
        ),
        migrations.AddField(
            model_name='getquote',
            name='driver1_city',
            field=models.CharField(choices=[('a', 'New York'), ('b', 'Miami')], default='New York', max_length=100),
        ),
        migrations.AddField(
            model_name='getquote',
            name='driver1_date_of_birth',
            field=models.DateField(default='1901-10-10'),
        ),
        migrations.AddField(
            model_name='getquote',
            name='driver1_first_name',
            field=models.CharField(default='1922', help_text='This is the help text!', max_length=100),
        ),
        migrations.AddField(
            model_name='getquote',
            name='driver1_last_name',
            field=models.CharField(default='1922', max_length=100),
        ),
        migrations.AddField(
            model_name='getquote',
            name='driver1_middle_name',
            field=models.CharField(default='1922', max_length=100),
        ),
        migrations.AddField(
            model_name='getquote',
            name='driver1_state',
            field=models.CharField(default='1922', max_length=100),
        ),
        migrations.AddField(
            model_name='getquote',
            name='driver1_street_address',
            field=models.CharField(default='1922', max_length=250),
        ),
        migrations.AddField(
            model_name='getquote',
            name='driver2_city',
            field=models.CharField(blank=True, choices=[('a', 'New York'), ('b', 'Miami')], default='LA', max_length=100),
        ),
        migrations.AddField(
            model_name='getquote',
            name='driver2_date_of_birth',
            field=models.DateField(blank=True, default='1902-10-10'),
        ),
        migrations.AddField(
            model_name='getquote',
            name='driver2_first_name',
            field=models.CharField(blank=True, default='1922', help_text='This is the help text!', max_length=100),
        ),
        migrations.AddField(
            model_name='getquote',
            name='driver2_last_name',
            field=models.CharField(blank=True, default='1922', max_length=100),
        ),
        migrations.AddField(
            model_name='getquote',
            name='driver2_middle_name',
            field=models.CharField(blank=True, default='1922', max_length=100),
        ),
        migrations.AddField(
            model_name='getquote',
            name='driver2_state',
            field=models.CharField(blank=True, default='1922', max_length=100),
        ),
        migrations.AddField(
            model_name='getquote',
            name='driver2_street_address',
            field=models.CharField(blank=True, default='1922', max_length=250),
        ),
        migrations.AddField(
            model_name='getquote',
            name='driver_confirmation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
        migrations.AddField(
            model_name='getquote',
            name='make',
            field=models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW')], default='BMW', max_length=100),
        ),
        migrations.AddField(
            model_name='getquote',
            name='vin',
            field=models.CharField(default='IASJI21ej22', max_length=100),
        ),
        migrations.AddField(
            model_name='getquote',
            name='year',
            field=models.CharField(choices=[('1982', '1982'), ('1983', '1983')], default='1922', max_length=4),
        ),
    ]
