# Generated by Django 2.1.2 on 2018-10-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonsured', '0002_getquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='getquote',
            name='body_style',
            field=models.CharField(choices=[('style1', 'body style 1'), ('style2', 'body style 2')], default='style1', max_length=100),
        ),
        migrations.AddField(
            model_name='getquote',
            name='car_model',
            field=models.CharField(choices=[('3 series', '3 series'), ('X3', 'X3')], default='X3', max_length=100),
        ),
        migrations.AddField(
            model_name='getquote',
            name='make',
            field=models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW')], default='BMW', max_length=100),
        ),
        migrations.AddField(
            model_name='getquote',
            name='vin',
            field=models.CharField(default='IASJI21ej22', max_length=100),
        ),
        migrations.AddField(
            model_name='getquote',
            name='year',
            field=models.CharField(choices=[('1982', '1982'), ('1983', '1983')], default='1922', max_length=4),
        ),
    ]
