# Generated by Django 2.1.2 on 2018-10-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonsured', '0004_auto_20181019_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='getquote',
            name='social_security_no',
            field=models.IntegerField(default=32035235),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='getquote',
            name='contact_phone',
            field=models.IntegerField(),
        ),
    ]
