# Generated by Django 2.1.2 on 2018-10-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonsured', '0005_auto_20181020_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='getquote',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=100),
        ),
        migrations.AddField(
            model_name='getquote',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], default='Married', max_length=100),
        ),
    ]
