# Generated by Django 2.1.2 on 2018-10-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonsured', '0006_auto_20181020_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='getquote',
            name='driver1_military',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
        migrations.AddField(
            model_name='getquote',
            name='driver2_military',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
        migrations.AddField(
            model_name='getquote',
            name='driver_license_age',
            field=models.IntegerField(default=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='getquote',
            name='driver_license_number',
            field=models.CharField(default='XXXXXX', max_length=150),
        ),
    ]
