# Generated by Django 2.1.2 on 2018-10-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonsured', '0007_auto_20181020_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='getquote',
            name='finance',
            field=models.CharField(choices=[('Loan', 'Loan'), ('Lease', 'Lease'), ('Own', 'Own')], default='Own', max_length=50),
        ),
    ]
