# Generated by Django 2.1.2 on 2018-10-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonsured', '0008_getquote_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='getquote',
            name='primary_use',
            field=models.CharField(choices=[('Personal', 'Work, school, pleasure'), ('Business', 'Business at least 50\\% of the time'), ('Farm', 'Used primarly on a Farm or Ranch'), ('Federal Gov Employee', 'Federal Gov Employee')], default='Personal', max_length=50),
        ),
    ]
