# Generated by Django 2.1.2 on 2018-10-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonsured', '0010_auto_20181020_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='getquote',
            name='insurance_coverage',
            field=models.CharField(choices=[('$5,000', '$5,000'), ('$10,000', '$10,000'), ('$15,000', '$15,000'), ('$20,000', '$20,000')], default='$5000', max_length=50),
        ),
    ]
